#pragma once

#include "utilities/aliases.hpp"
#include "utilities/constants.hpp"

namespace Lilliputian
{
	class Component
	{
	public:
		enum ComponentType
		{
			COMPONENT_TYPE_NONE,
			COMPONENT_TYPE_AI_BEHAVIOUR_TREE,
			COMPONENT_TYPE_AI_SIGHT_PERCEPTION,
			COMPONENT_TYPE_AI_SOUND_PERCEPTION,
			COMPONENT_TYPE_ANIMATED_SPRITE_2D,
			COMPONENT_TYPE_AUDIO_LISTENER_2D,
			COMPONENT_TYPE_CAMERA_2D,
			COMPONENT_TYPE_CIRCLE_COLLIDER_2D,
			COMPONENT_TYPE_CONSTANT_DIRECTIONAL_FORCE_2D,
			COMPONENT_TYPE_CONSTANT_POINT_FORCE_2D,
			COMPONENT_TYPE_COUNTDOWN_TIMER,
			COMPONENT_TYPE_FIXED_TRANSFORM_2D,
			COMPONENT_TYPE_NAVIGATION_MESH_2D,
			COMPONENT_TYPE_NAVIGATION_MESH_AGENT_2D,
			COMPONENT_TYPE_NAVIGATION_MESH_BOX_OBSTACLE_2D,
			COMPONENT_TYPE_NAVIGATION_PATH_2D,
			COMPONENT_TYPE_NEURAL_NETWORK,
			COMPONENT_TYPE_PHYSICS_CONSTRAINT_2D,
			COMPONENT_TYPE_PHYSICS_THRUSTER_2D,
			COMPONENT_TYPE_PROPERTY_ANIMATION,
			COMPONENT_TYPE_RECTANGULAR_COLIIDER_2D,
			COMPONENT_TYPE_RECTANGULAR_MESH_2D,
			COMPONENT_TYPE_RECTANGULAR_TRIGGER_AREA_2D,
			COMPONENT_TYPE_REGULAR_POLYGONAL_MESH_2D,
			COMPONENT_TYPE_RIGID_BODY_2D,
			COMPONENT_TYPE_SPRITE,
			COMPONENT_TYPE_STATIC_FLUID_2D,
			COMPONENT_TYPE_STREAMED_AUDIO_SOURCE_2D,
			COMPONENT_TYPE_UI_BUTTON,
			COMPONENT_TYPE_UI_COLOURED_RECTANGLE,
			COMPONENT_TYPE_UI_GRAPH_EDIT,
			COMPONENT_TYPE_UI_GRAPH_NODE,
			COMPONENT_TYPE_UI_HORIZONTAL_SCROLLBAR,
			COMPONENT_TYPE_UI_HORIZONTAL_SEPARATOR,
			COMPONENT_TYPE_UI_HORIZONTAL_SLIDER,
			COMPONENT_TYPE_UI_HOVER_CARD,
			COMPONENT_TYPE_UI_ITEM_LIST,
			COMPONENT_TYPE_UI_LINK_BUTTON,
			COMPONENT_TYPE_UI_PANEL,
			COMPONENT_TYPE_UI_PROGRESS_BAR,
			COMPONENT_TYPE_UI_RICH_TEXT_LABEL,
			COMPONENT_TYPE_UI_SPIN_BOX,
			COMPONENT_TYPE_UI_TAB,
			COMPONENT_TYPE_UI_TEXT_EDIT,
			COMPONENT_TYPE_UI_TEXT_LABEL,
			COMPONENT_TYPE_UI_TEXTURED_BUTTON,
			COMPONENT_TYPE_UI_TEXTURED_PROGRESS_BAR,
			COMPONENT_TYPE_UI_TEXTURED_RECTANGLE,
			COMPONENT_TYPE_UI_TREE,
			COMPONENT_TYPE_UI_VERTICAL_SCROLLBAR,
			COMPONENT_TYPE_UI_VERTICAL_SEPARATOR,
			COMPONENT_TYPE_UI_VERTICAL_SLIDER
		};

		EntityID entityID = NO_ENTITY;
	private:
	};
}